### ISSUE TITLE
Need more visual options...

### ISSUE THREAD

**Issue by kappaknight** [guacamoly/semantic-ui-kit-for-sketch#1]
Hey, this is a great start, but this Sketch file really needs more pieces to select from.

For example, while there's an error state for the input fields, there are no regular states, or even input fields of various sizes.

This has already helped me save some time, but would love to see it expanded to way more options, hopefully similar to what's being demo'ed on the Semantic-UI website in terms of visual options.

**Comment by ArnaudValensi** [comment]
There is other projects with different elements:
https://github.com/garystover/Semantic-UI-Kit
https://github.com/mikefats/semantic-ui-kit

**Comment by dmulter** [comment]
The first link above is broken, and the second one can't be downloaded. Really would love a big sketch file with all the components!

**Comment by guacamoly** [comment]
Starting to cleanup and update slowly @dmulter,
Any suggestions on what components should be added to the file?  The variability and modularity of the semantic framework is a bit intimidating. Hard to pick which elements belong in the ui kit.

**Comment by dmulter** [comment]
Yeah, looked like a giant effort to me. Semantic UI is so awesome though, it's a shame there isn't great support for Sketch. Wish I was actually a designer guy...
