### ISSUE TITLE
Any updates on this repo?

### ISSUE THREAD

**Issue by alejandronanez** [guacamoly/semantic-ui-kit-for-sketch#3]
Hey guys! We really like Semantic but the repo is a little bit outdated.

Any plans to add more content into the sketch file?

Thanks!!!!

**Comment by guacamoly** [comment]
Apologies to the community for not keeping this repo up to date, or improving it.
I will slowly start adding to this sketch file and try to update with the latest sketch ui as much as possible. I welcome others to contribute as well.  Perhaps splitting up the designs into smaller components will help in splitting the loadif others are willing.

**Comment by krajasekhar** [comment]
Any update on this. Thanks.

**Comment by guacamoly** [comment]
Hey @krajasekhar @alejandronanez, I haven't had a change to really work on this project more. The sketch file is free for open collaboration. Please feel free to make/contribute any changes you feel could be useful, however small. I have not worked with semantic ui in a little while given so many other frameworks and libraries are available. I'm not sure when I will get some time to work on this some more. 
my apologies.
